#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ../ebin

-mode(compile).

main(Args) ->
    eclip:parse(Args, spec(), #{}).

spec() ->
    #{opts => [#{short => $n, long => "number-of-sites", default => 1},
               #{short => $H, long => "number-of-hosts", default => 1}],
      cb => fun do_cmd/4}.

do_cmd(_, _, N, H) ->
    io:format("N=~p H=~p\n", [N, H]).


