#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ../../ebin

main(Args) ->
    eclip:parse(Args, spec(), #{}).

spec() ->
    #{opts => [#{short => $i, type => int,
                 default => 1, default_in_help => false}],
      args => [#{name => name, type => {enum, [foo, bar]}}]}.
