#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ../../ebin

main(Args) ->
    eclip:parse(Args, spec(), #{}).

spec() ->
    #{opts => [#{short => $x, type => int,
                 default => 1, default_in_help => false},
               #{short => $s, type => string,
                 default_in_help => false}],
      args => [#{name => name, type => {enum, [foo, bar]}}]}.
